#ifndef __DEFINATION_H__
#define __DEFINATION_H__

#include "cocos2d.h"

using std::vector;

const float SCHEDULE_TRANSITION_TIME = 3;
const float TRANSITION_TIME = 1;
const float GROUND_THICKNESS = 160;
const float GAME_GROUND_THICKNESS = 190;
const float TANK_SPAWN_TIME = 6;
const float TANK_RELOAD_DURATION = 1;
const float MISSILE_FLYING_DURATION = 1;
const float RANGE_MISSILE_SPAWN_DURATION = 4;
const float RANGE_MISSILE_FLYING_DURATION = 2;
const float ENERGY_TOWER_SPAWN_DURATION = 15;
const float TOWER_RELOAD_DURATION = 3;
const float GASCAN_SPAWN_DURATION = 20;
const float MINI_BOSS_PREPARE_DURATION = 3;
const float BIG_BOSS_PREPARE_DURATION = 3;
const float GASCAN_FALLING_DURATION = 7;

const int TOTAL_BULLET = 4;
const float TOWER_BULLET_DURATION = 3;

enum IntroductionSceneProperties
{
	HELICOPTER_COMING_DURATION = 7,
	HELICOPTER_LANDING_DURATION = 5,
	HELICOPTER_LEAVING_DURATION = 6,
	HELICOPTER_LOST_CONTROLL_DURATION = 3,
	SOLDIER_MOVING_DURATION = 3
};

enum CollisionBitmask
{
	OBSTACLE_COLLISION_BITMASK,
	PLAYER_COLLISTION_BITMASK,
	PLAYER_BULLET_BITMASK,
	ENEMY_BULLET_BISMASK,
	ENEMY_COLLISION_BITMASK,
	GASCAN_COLLISION_BITMASK,
	BOSS_COLLISION_BITMASK
};


#endif //__DEFINATION_H__